version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kanari
      POSTGRES_PASSWORD: kanari
      POSTGRES_DB: kanari
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  gateway:
    build:
      context: .
      dockerfile: deploy/docker/gateway.Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://kanari:kanari@postgres:5432/kanari
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  llm-service:
    build:
      context: .
      dockerfile: deploy/docker/llm-service.Dockerfile
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: deploy/docker/worker.Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://kanari:kanari@postgres:5432/kanari
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:

