name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install (tolerant until scaffold complete)
        run: pnpm install || true
      - name: Lint
        run: pnpm -r lint || true
      - name: Test
        run: pnpm -r test || true
      - name: Build
        run: pnpm -r build || true

